# Generated by Django 3.1.7 on 2021-03-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210311_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer Text'),
        ),
        migrations.AddField(
            model_name='answers',
            name='is_right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=225, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date_created'),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
    ]
